version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Change this to a strong password
    volumes:
      - postgresdata:/var/lib/postgresql/data  # Persist data volume
    networks:
      - mumo-net

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: morismumo28@gmail.com  # Change this to a valid email
      PGADMIN_DEFAULT_PASSWORD: '123Mor!@#'  # Change this to a strong password
    ports:
      - "5050:80"  # Map port 5050 on host to container port 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - mumo-net

  pyspark_notebook:
    image: quay.io/jupyter/pyspark-notebook:latest
    ports:
      - "8888:8888"
      - "4040-4041:4040-4041"
    volumes:
      - ~/programs/volumes/pysparkdata:/pysparkdata
    depends_on:
      - postgres
    networks:
      - mumo-net

networks:
  mumo-net: {}

volumes:
  postgresdata: {}
  pgadmin: {}