version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Change this to a strong password
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persist data volume
    networks:
      - my-net

  pgadmin4:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: morismumo28@gmail.com  # Change this to a valid email
      PGADMIN_DEFAULT_PASSWORD: password  # Change this to a strong password
    ports:
      - "5050:80"  # Map port 5050 on host to container port 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - my-net

volumes:
  postgres_data: {}  # Define empty volume for persistence
  pgadmin: {}

networks:
  my-net: {}  # Define empty network
